# Generated by Django 5.1.3 on 2024-12-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('material', models.CharField(max_length=32)),
                ('lifetime_use', models.CharField(max_length=32)),
                ('lifetime_manufacture', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type_ppe', models.CharField(max_length=32, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='logo/')),
                ('name_ppe', models.CharField(max_length=32)),
                ('standard_ppe', models.CharField(max_length=32)),
                ('manual_for_revision', models.FileField(upload_to='manuals/')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='revisions.expiration')),
                ('group_type_ppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='revisions.typeofppe')),
            ],
        ),
    ]
