# Generated by Django 5.1.3 on 2024-12-13 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('revisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
            },
        ),
        migrations.CreateModel(
            name='StandardPpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='revision',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='group_type_ppe',
        ),
        migrations.AddField(
            model_name='typeofppe',
            name='image',
            field=models.ImageField(default=None, upload_to='logo/'),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('lifetime_use_months', models.IntegerField(help_text='Maximální doba používání v měsících')),
                ('lifetime_manufacture_years', models.IntegerField(help_text='Maximální doba od data výroby v letech')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturers', to='revisions.materialtype')),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RevisionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='logo/')),
                ('name_ppe', models.CharField(max_length=32)),
                ('manual_for_revision', models.FileField(upload_to='manuals/')),
                ('notes', models.TextField()),
                ('group_type_ppe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revisions.typeofppe')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', related_query_name='revision', to='revisions.manufacturer')),
                ('standard_ppe', models.ManyToManyField(related_name='revision_data', to='revisions.standardppe')),
            ],
            options={
                'verbose_name': 'Revision Data',
                'verbose_name_plural': 'Revision Data',
            },
        ),
        migrations.CreateModel(
            name='RevisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('date_manufacture', models.DateField()),
                ('date_of_first_use', models.DateField()),
                ('date_of_revision', models.DateField(blank=True, null=True)),
                ('date_of_next_revision', models.DateField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('new', 'New'), ('fit', 'Fit to Use'), ('retire', 'Retire')], max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revision_records', to=settings.AUTH_USER_MODEL)),
                ('item_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revision_records', related_query_name='revision_record', to='accounts.itemgroup')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revisions.revisiondata')),
            ],
        ),
        migrations.DeleteModel(
            name='Expiration',
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
