# Generated by Django 5.1.3 on 2024-12-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0002_materialtype_standardppe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardppe',
            options={'verbose_name': 'Standard PPE', 'verbose_name_plural': 'Standards PPE'},
        ),
        migrations.AlterModelOptions(
            name='typeofppe',
            options={'verbose_name': 'Type of PPE', 'verbose_name_plural': 'Types of PPE'},
        ),
        migrations.AddField(
            model_name='standardppe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
