# Generated by Django 5.1.3 on 2024-12-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0003_alter_standardppe_options_alter_typeofppe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardppe',
            options={'ordering': ['code'], 'verbose_name': 'Standard PPE', 'verbose_name_plural': 'Standards PPE'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='lifetime_manufacture_years',
            field=models.IntegerField(help_text='Maximální doba používání od data výroby v letech'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='lifetime_use_months',
            field=models.IntegerField(help_text='Maximální doba používání v letech'),
        ),
    ]
