# Generated by Django 5.1.3 on 2024-12-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0004_alter_standardppe_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='lifetime_use_months',
            new_name='lifetime_use_years',
        ),
    ]
