# Generated by Django 5.1.3 on 2024-12-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0005_rename_lifetime_use_months_manufacturer_lifetime_use_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='lifetime_use_years',
            field=models.IntegerField(help_text='Maximální doba používání od 1.použití v letech'),
        ),
        migrations.AddConstraint(
            model_name='revisiondata',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name_ppe'), name='unique_manufacturer_name_ppe'),
        ),
    ]
