# Generated by Django 5.1.3 on 2024-12-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0006_alter_manufacturer_lifetime_use_years_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='revisiondata',
            name='unique_manufacturer_name_ppe',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='lifetime_use_years',
            field=models.IntegerField(help_text='Maximální doba používání v letech'),
        ),
    ]
