# Generated by Django 5.1.3 on 2024-12-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0007_remove_revisiondata_unique_manufacturer_name_ppe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='lifetime_use_years',
            field=models.IntegerField(help_text='Maximální doba používání od 1.použití v letech'),
        ),
        migrations.AlterField(
            model_name='revisionrecord',
            name='verdict',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('fit', 'Fit to Use'), ('retire', 'Retire'), ('Fit Until', 'Fit Until')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='revisiondata',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name_ppe'), name='unique_manufacturer_name_ppe'),
        ),
    ]
