# Generated by Django 5.1.3 on 2024-12-17 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_country_options_and_more'),
        ('revisions', '0008_alter_manufacturer_lifetime_use_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_type', to='revisions.materialtype'),
        ),
        migrations.AlterField(
            model_name='revisiondata',
            name='group_type_ppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_type', to='revisions.typeofppe'),
        ),
        migrations.AlterField(
            model_name='revisiondata',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', related_query_name='manufacturer', to='revisions.manufacturer'),
        ),
        migrations.AlterField(
            model_name='revisiondata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revisiondata',
            name='standard_ppe',
            field=models.ManyToManyField(related_name='standard_ppe', to='revisions.standardppe'),
        ),
        migrations.AlterField(
            model_name='revisionrecord',
            name='date_manufacture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revisionrecord',
            name='date_of_first_use',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revisionrecord',
            name='item_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_group', related_query_name='item_group', to='accounts.itemgroup'),
        ),
        migrations.AlterField(
            model_name='typeofppe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logo/'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(fields=('name', 'material_type'), name='unique_constraint_material_type'),
        ),
    ]
