# Generated by Django 5.1.3 on 2025-01-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0009_alter_manufacturer_material_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifetimeOfPpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_use_years', models.IntegerField(help_text='Maximální doba používání od 1.použití v letech')),
                ('lifetime_manufacture_years', models.IntegerField(help_text='Maximální doba používání od data výroby v letech')),
            ],
            options={
                'verbose_name_plural': 'Lifetime of PPE',
                'ordering': ['manufacturer', 'material_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='manufacturer',
            name='unique_constraint_material_type',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='lifetime_manufacture_years',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='lifetime_use_years',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='revisiondata',
            name='image',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/manufacturer_logo/'),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='static/material/'),
        ),
        migrations.AddField(
            model_name='revisiondata',
            name='image_items',
            field=models.ImageField(default=None, upload_to='revision_data/'),
        ),
        migrations.AddField(
            model_name='revisionrecord',
            name='photo_of_item',
            field=models.ImageField(blank=True, null=True, upload_to='revision_record/'),
        ),
        migrations.AlterField(
            model_name='typeofppe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/type_of_ppe/'),
        ),
        migrations.AddField(
            model_name='lifetimeofppe',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifetime', to='revisions.manufacturer'),
        ),
        migrations.AddField(
            model_name='lifetimeofppe',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_type', to='revisions.materialtype'),
        ),
        migrations.AddConstraint(
            model_name='lifetimeofppe',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'material_type'), name='unique_constraint_material_type'),
        ),
    ]
