# Generated by Django 5.1.3 on 2025-01-03 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0010_lifetimeofppe_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='revisiondata',
            name='unique_manufacturer_name_ppe',
        ),
        migrations.RemoveField(
            model_name='revisiondata',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='revisiondata',
            name='lifetime_of_ppe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='revision_data', related_query_name='revision_data', to='revisions.lifetimeofppe'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='revisiondata',
            constraint=models.UniqueConstraint(fields=('lifetime_of_ppe', 'name_ppe'), name='unique_lifetime_name_ppe'),
        ),
    ]
