# Generated by Django 5.1.3 on 2025-01-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0011_remove_revisiondata_unique_manufacturer_name_ppe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/manufacturer/logo/'),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/material/'),
        ),
        migrations.AlterField(
            model_name='revisiondata',
            name='image_items',
            field=models.ImageField(default=None, upload_to='static/image/revision_data/'),
        ),
        migrations.AlterField(
            model_name='revisiondata',
            name='manual_for_revision',
            field=models.FileField(upload_to='static/revision_data/manuals/'),
        ),
        migrations.AlterField(
            model_name='revisionrecord',
            name='photo_of_item',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/revision_record/'),
        ),
        migrations.AlterField(
            model_name='standardppe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/standard_ppe/logo/'),
        ),
        migrations.AlterField(
            model_name='typeofppe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/image/type_of_ppe/'),
        ),
    ]
