# Generated by Django 5.1.3 on 2025-01-07 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
        ('revisions', '0012_alter_manufacturer_logo_alter_materialtype_symbol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddConstraint(
            model_name='revisionrecord',
            constraint=models.UniqueConstraint(fields=('serial_number', 'owner', 'item_group', 'revision_data'), name='unique_serial_owner_group_revision_record'),
        ),
    ]
