"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import logging
import os
from pathlib import Path
from dotenv import load_dotenv

# TODO da se provest regex nad databazi v Django?

# Nastavení základní cesty projektu: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Načíst proměnné prostředí ze souboru .env
load_dotenv()

# VAROVÁNÍ: tajný klíč používaný v produkci uchovávejte v tajnosti!
SECRET_KEY = os.getenv("SECRET_KEY", default="change-this-to-a-secure-one")

# Aplikace: seznam všech nainstalovaných aplikací v projektu
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Externí knihovny
    'django_dump_load_utf8',
    # hlavni app
    'config',
    # Vlastní aplikace
    'accounts.apps.AccountsConfig',
    'calculator',
    'revisions',
]

# Nastavení vlastního modelu uživatele
AUTH_USER_MODEL = 'accounts.CustomUser'

# Middleware: zpracování požadavků a odpovědí
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Nastavení úrovně zpráv Django messages frameworku
from django.contrib.messages import constants as message_constants
MESSAGE_LEVEL = message_constants.INFO  # Nastavení výchozí úrovně zpráv

# Konfigurace URL
ROOT_URLCONF = 'config.urls'

# Nastavení šablon
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.user_groups_status',
            ],
        },
    },
]

# WSGI aplikace
WSGI_APPLICATION = 'config.wsgi.application'

# Ověřování hesel
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Mezinárodní nastavení
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'CET'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('cs', 'Čeština'),
]

# Statické soubory (CSS, JavaScript, obrázky)
# Před nasazením do produkce: python manage.py collectstatic
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Datové soubory
# TODO pohlidat si MEDIA_ROOT -> pokud bude problem tak ponechat pouze BASE_DIR #/ 'media'
MEDIA_ROOT = BASE_DIR
MEDIA_URL = '/media/'


# Výchozí primární klíčová pole
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Přihlašovací odkazy pro aplikaci accounts
LOGIN_REDIRECT_URL = 'login_success'
LOGOUT_REDIRECT_URL = 'home'

LOGGING = {
       'version': 1,
       'disable_existing_loggers': False,
       'formatters': {
           'verbose': {
               'format': '{levelname} {asctime} {module} {message}',
               'style': '{',
           },
           'simple': {
               'format': '{levelname} {message}',
               'style': '{',
           },
       },
       'handlers': {
           'console': {
               'class': logging.StreamHandler,
               'formatter': 'simple',
           },
           'file': {
               'class': logging.FileHandler,
               'filename': BASE_DIR / 'logs/django.log',
               'formatter': 'verbose',
           },
       },
       'root': {
           'handlers': ['console', 'file'],
           'level': 'DEBUG',
       },
       'loggers': {
           'django': {
               'handlers': ['console', 'file'],
               'level': 'INFO',
               'propagate': False,
           },
           'django.request': {
               'handlers': ['file'],
               'level': 'ERROR',
               'propagate': False,
           },
       },
   }